version: '3'
services: 
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    container_name: bolovkh-my-netology-hw
    command:
      --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - bolovkh-netology-hw
    restart: always
  pushgateway:
    image: prom/pushgateway:v1.6.2
    container_name: bolovkh-pushgateway
    ports:
      - 9091:9091
    networks:
      - bolovkh-netology-hw
    depends_on:
      - prometheus
    restart: unless-stopped
  grafana:
    image: grafana/grafana
    container_name: bolovkh-netology-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=netology
      - GF_SECURITY_ADMIN_PASSWORD=netology
    ports:
      - 90:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./custom.ini:/etc/grafana/grafana.ini
    networks:
      - bolovkh-netology-hw
    depends_on:
      - pushgateway
    restart: unless-stopped
volumes:
  prometheus-data:
  grafana-data:
networks:
  bolovkh-netology-hw:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
